pub mod titlebar;
pub mod custom_widget;
pub mod frame;
pub mod split;
pub mod sidebar;
pub mod tool_tab;
pub mod menu;
pub mod list_tile;
pub mod responsible_tilebutton;
pub mod main_view;
// pub mod sidebar_button;